#!/usr/bin/env python3
"""
Generate Swift normalization constants from chewnet_norm.json.

This script reads the normalization parameters from the trained model and generates
a Swift file with the FEATURE_MEAN and FEATURE_STD arrays that can be directly
imported into the iOS/macOS app, eliminating manual synchronization errors.

Usage:
    python generate_swift_constants.py --input exports/chewnet_norm.json --output Generated/NormalizationConstants.swift
"""

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Optional


def format_swift_array(values: list[float], indent: str = "    ") -> str:
    """Format a list of floats as a Swift array with proper indentation."""
    formatted_values = [f"{v:.10f}" for v in values]
    return f"[\n{indent}    " + f",\n{indent}    ".join(formatted_values) + f"\n{indent}]"


def generate_swift_constants(
    norm_json_path: Path,
    output_path: Path,
    wandb_run_id: Optional[str] = None,
    wandb_run_url: Optional[str] = None,
    model_version: Optional[str] = None,
) -> None:
    """
    Generate Swift constants file from normalization JSON.
    
    Args:
        norm_json_path: Path to chewnet_norm.json
        output_path: Path where Swift file should be written
        wandb_run_id: Optional W&B run ID for traceability
        wandb_run_url: Optional W&B run URL for traceability
        model_version: Optional model version string
    """
    # Load normalization parameters
    with open(norm_json_path, 'r') as f:
        norm_data = json.load(f)
    
    feature_mean = norm_data['feature_mean']
    feature_std = norm_data['feature_std']
    
    # Validate arrays have correct length (12 features)
    assert len(feature_mean) == 12, f"Expected 12 features, got {len(feature_mean)}"
    assert len(feature_std) == 12, f"Expected 12 features, got {len(feature_std)}"
    
    # Generate timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Build header comments
    header = f"""//
//  NormalizationConstants.swift
//  ChewSense
//
//  AUTO-GENERATED by generate_swift_constants.py
//  Do not edit this file manually - regenerate from pipeline after training
//
//  Generated: {timestamp}
"""
    
    if model_version:
        header += f"//  Model Version: {model_version}\n"
    if wandb_run_id:
        header += f"//  W&B Run ID: {wandb_run_id}\n"
    if wandb_run_url:
        header += f"//  W&B Run URL: {wandb_run_url}\n"
    
    header += "//\n\nimport Foundation\n\n"
    
    # Build constants
    constants = f"""/// Normalization constants for ChewNet feature preprocessing.
/// These values are computed from the training set and must match the model's expectations.
struct NormalizationConstants {{
    
    /// Feature means from training data (12 features)
    /// Order: [mean_accel_mag, var_accel_mag, rms_accel_mag, mean_gyro_mag, rms_gyro_mag,
    ///         rms_jerk, zcr_accel_mag, chew_bandpower_1_3hz, bandpower_0_8_1_5hz,
    ///         bandpower_2_4hz, spectral_centroid, spectral_rolloff_0_85]
    static let FEATURE_MEAN: [Double] = {format_swift_array(feature_mean)}
    
    /// Feature standard deviations from training data (12 features)
    static let FEATURE_STD: [Double] = {format_swift_array(feature_std)}
    
    /// Normalize features using training statistics
    /// - Parameter features: Raw feature vector (12 elements)
    /// - Returns: Normalized feature vector
    static func normalize(_ features: [Double]) -> [Double] {{
        guard features.count == 12 else {{
            fatalError("Expected 12 features, got \\(features.count)")
        }}
        return zip(zip(features, FEATURE_MEAN), FEATURE_STD).map {{ (($0.0 - $0.1) / $1) }}
    }}
}}
"""
    
    # Write output file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header)
        f.write(constants)
    
    print(f"✅ Generated Swift constants: {output_path}")
    print(f"   FEATURE_MEAN: {len(feature_mean)} values")
    print(f"   FEATURE_STD: {len(feature_std)} values")
    if wandb_run_id:
        print(f"   W&B Run: {wandb_run_id}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate Swift normalization constants from chewnet_norm.json"
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("exports/chewnet_norm.json"),
        help="Path to chewnet_norm.json"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("../04-RealWorldTesting/Generated/NormalizationConstants.swift"),
        help="Output path for Swift file"
    )
    parser.add_argument(
        "--model-checkpoint",
        type=Path,
        default=Path("models/chewnet.pth"),
        help="Path to model checkpoint (to extract W&B metadata)"
    )
    parser.add_argument(
        "--model-version",
        type=str,
        default=None,
        help="Model version string (e.g., 'v1.0')"
    )
    
    args = parser.parse_args()
    
    # Try to extract W&B metadata from checkpoint if available
    wandb_run_id = None
    wandb_run_url = None
    
    if args.model_checkpoint.exists():
        try:
            import torch
            checkpoint = torch.load(args.model_checkpoint, map_location='cpu', weights_only=False)
            wandb_run_id = checkpoint.get('wandb_run_id')
            wandb_run_url = checkpoint.get('wandb_run_url')
        except Exception as e:
            print(f"Warning: Could not load checkpoint metadata: {e}")
    
    generate_swift_constants(
        norm_json_path=args.input,
        output_path=args.output,
        wandb_run_id=wandb_run_id,
        wandb_run_url=wandb_run_url,
        model_version=args.model_version,
    )


if __name__ == "__main__":
    main()
