import pandas as pd
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

# Load the manually labeled data (#1)
manual_df = pd.read_csv('step6.csv')

# Load the features generated by OpenCV (#2)
features_df = pd.read_csv('step1.csv')

# Merge the two datasets on the 'frame' column
merged_df = pd.merge(features_df, manual_df[['frame', 'teeth', 'lips', 'action']], on='frame')

# Encode the target variables (teeth, lips, and action)
le_teeth = LabelEncoder()
le_lips = LabelEncoder()
le_action = LabelEncoder()

merged_df['teeth_encoded'] = le_teeth.fit_transform(merged_df['teeth'])
merged_df['lips_encoded'] = le_lips.fit_transform(merged_df['lips'])
merged_df['action_encoded'] = le_action.fit_transform(merged_df['action'])

# Define features and targets
X = merged_df.drop(columns=['frame', 'timestamp', 'teeth', 'lips', 'action', 'teeth_encoded', 'lips_encoded', 'action_encoded'])
y_teeth = merged_df['teeth_encoded']
y_lips = merged_df['lips_encoded']
y_action = merged_df['action_encoded']

# Split data into training and testing sets
X_train, X_test, y_train_teeth, y_test_teeth = train_test_split(X, y_teeth, test_size=0.2, random_state=42)
X_train, X_test, y_train_lips, y_test_lips = train_test_split(X, y_lips, test_size=0.2, random_state=42)
X_train, X_test, y_train_action, y_test_action = train_test_split(X, y_action, test_size=0.2, random_state=42)

# Train a RandomForestClassifier for each target variable
clf_teeth = RandomForestClassifier(random_state=42)
clf_lips = RandomForestClassifier(random_state=42)
clf_action = RandomForestClassifier(random_state=42)

clf_teeth.fit(X_train, y_train_teeth)
clf_lips.fit(X_train, y_train_lips)
clf_action.fit(X_train, y_train_action)

# Predict on the test set
y_pred_teeth = clf_teeth.predict(X_test)
y_pred_lips = clf_lips.predict(X_test)
y_pred_action = clf_action.predict(X_test)

# Print classification reports
print("Classification Report for Teeth:")
print(classification_report(y_test_teeth, y_pred_teeth, target_names=le_teeth.classes_))

print("\nClassification Report for Lips:")
print(classification_report(y_test_lips, y_pred_lips, target_names=le_lips.classes_))

print("\nClassification Report for Action:")
print(classification_report(y_test_action, y_pred_action, target_names=le_action.classes_))

# Extract feature importances to determine thresholds
importances_teeth = clf_teeth.feature_importances_
importances_lips = clf_lips.feature_importances_
importances_action = clf_action.feature_importances_

# Display the most important features
feature_names = X.columns

teeth_thresholds = sorted(zip(importances_teeth, feature_names), reverse=True)
lips_thresholds = sorted(zip(importances_lips, feature_names), reverse=True)
action_thresholds = sorted(zip(importances_action, feature_names), reverse=True)

print("\nTop features for Teeth prediction:")
for importance, name in teeth_thresholds[:5]:
    print(f"{name}: {importance:.4f}")

print("\nTop features for Lips prediction:")
for importance, name in lips_thresholds[:5]:
    print(f"{name}: {importance:.4f}")

print("\nTop features for Action prediction:")
for importance, name in action_thresholds[:5]:
    print(f"{name}: {importance:.4f}")
