columnHeaders:
    5: ["P05X", "P05Y"]
    7: ["P07X", "P07Y"]
    9: ["P09X", "P09Y"]
    11: ["P11X", "P11Y"]
    13: ["P13X", "P13Y"]
    49: ["P49X", "P49Y"]
    51: ["P51X", "P51Y"]
    52: ["P52X", "P52Y"]
    53: ["P53X", "P53Y"]
    55: ["P55X", "P55Y"]
    57: ["P57X", "P57Y"] 
    58: ["P58X", "P58Y"]
    59: ["P59X", "P59Y"] 
    62: ["P62X", "P62Y"]
    64: ["P64X", "P64Y"]
    66: ["P66X", "P66Y"]
    68: ["P68X", "P68Y"]
lines:
    - [5, 7]
    - [5, 9]
    - [5, 11]
    - [5, 13]
    - [7, 9]
    - [7, 11]
    - [7, 13]
    - [9, 11]
    - [9, 13]
    - [11, 13]
    - [49, 55]
    - [52, 58]
    - [62, 57]
    - [64, 59]
    - [68, 53]
    - [66, 51]
    - [5, 49]
    - [5, 52]
    - [5, 55]
    - [5, 58]
    - [5, 62]
    - [5, 64]
    - [5, 66]
    - [5, 68]
    - [7, 49]
    - [7, 52]
    - [7, 55]
    - [7, 58]
    - [7, 62]
    - [7, 64]
    - [7, 66]
    - [7, 68]
    - [9, 49]
    - [9, 52]
    - [9, 55]
    - [9, 58]
    - [9, 62]
    - [9, 64]
    - [9, 66]
    - [9, 68]
    - [11, 49]
    - [11, 52]
    - [11, 55]
    - [11, 58]
    - [11, 62]
    - [11, 64]
    - [11, 66]
    - [11, 68]
    - [13, 49]
    - [13, 52]
    - [13, 55]
    - [13, 58]
    - [13, 62]
    - [13, 64]
    - [13, 66]
    - [13, 68]
ratios:
    - [49, 55, 52, 58]
