"""
Deploy stage: Copy artifacts to Xcode project.

This stage copies the trained model and generated constants to the
iOS/macOS testing app, ensuring all references are up to date.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Optional

from .export import export_coreml, export_normalization_json, generate_swift_constants


# Default paths relative to repository root
DEFAULT_EXPORTS_DIR = "exports"
DEFAULT_XCODE_PROJECT = "04-RealWorldTesting/ChewSense-RealTime/ChewSenseDebuggingModel"
DEFAULT_GENERATED_DIR = "Generated"


def deploy_to_app(
    model_path: Path,
    repo_root: Path,
    exports_dir: Optional[Path] = None,
    xcode_project: Optional[Path] = None,
    force: bool = False,
) -> dict[str, Path]:
    """
    Deploy trained model and constants to Xcode project.
    
    This function:
    1. Exports CoreML model to exports/ and copies to Xcode project
    2. Exports normalization JSON to exports/
    3. Generates Swift constants and places in Xcode project's Generated/
    
    Args:
        model_path: Path to trained PyTorch checkpoint
        repo_root: Repository root directory
        exports_dir: Directory for export artifacts (default: exports/)
        xcode_project: Path to Xcode project source directory
        force: Overwrite existing files
    
    Returns:
        Dictionary of deployed file paths
    """
    model_path = Path(model_path)
    repo_root = Path(repo_root)
    
    if exports_dir is None:
        exports_dir = repo_root / "02-DataPipeline" / DEFAULT_EXPORTS_DIR
    else:
        exports_dir = Path(exports_dir)
    
    if xcode_project is None:
        xcode_project = repo_root / DEFAULT_XCODE_PROJECT
    else:
        xcode_project = Path(xcode_project)
    
    exports_dir.mkdir(parents=True, exist_ok=True)
    
    print("\n🚀 Deploying model to Xcode project...")
    print(f"   Model: {model_path}")
    print(f"   Exports: {exports_dir}")
    print(f"   Xcode: {xcode_project}")
    
    deployed = {}
    
    # 1. Export CoreML model
    mlpackage_export = exports_dir / "ChewNet.mlpackage"
    export_coreml(model_path, mlpackage_export)
    deployed["mlpackage_export"] = mlpackage_export
    
    # Copy to Xcode project root (where it's typically referenced)
    mlpackage_xcode = xcode_project.parent / "ChewNet.mlpackage"
    if mlpackage_xcode.exists():
        if force:
            shutil.rmtree(mlpackage_xcode)
        else:
            print(f"   ⚠️  Skipping (exists): {mlpackage_xcode}")
    
    if not mlpackage_xcode.exists():
        shutil.copytree(mlpackage_export, mlpackage_xcode)
        print(f"   ✅ Copied mlpackage: {mlpackage_xcode}")
    deployed["mlpackage_xcode"] = mlpackage_xcode
    
    # 2. Export normalization JSON
    norm_json = exports_dir / "chewnet_norm.json"
    export_normalization_json(model_path, norm_json)
    deployed["norm_json"] = norm_json
    
    # 3. Generate Swift constants
    generated_dir = xcode_project / DEFAULT_GENERATED_DIR
    generated_dir.mkdir(parents=True, exist_ok=True)
    
    swift_constants = generated_dir / "NormalizationConstants.swift"
    generate_swift_constants(model_path, swift_constants)
    deployed["swift_constants"] = swift_constants
    
    print("\n✅ Deployment complete!")
    print("\n📋 Next steps:")
    print("   1. Open the Xcode project")
    print("   2. Ensure ChewNet.mlpackage is added to the target")
    print(f"   3. Add {generated_dir.name}/NormalizationConstants.swift to the target")
    print("   4. Update ContentView.swift to use NormalizationConstants.normalize()")
    print("   5. Build and test on device with AirPods")
    
    return deployed


def create_deployment_readme(xcode_project: Path) -> Path:
    """Create a README in the Generated directory explaining the files."""
    generated_dir = Path(xcode_project) / DEFAULT_GENERATED_DIR
    generated_dir.mkdir(parents=True, exist_ok=True)
    
    readme_path = generated_dir / "README.md"
    
    content = '''# Generated Files

⚠️ **Do not edit these files manually!**

These files are auto-generated by the Python pipeline and should be
regenerated whenever you train a new model.

## Files

- `NormalizationConstants.swift` — Feature normalization constants and runtime config

## Regenerating

From the repository root:

```bash
cd 02-DataPipeline
python main.py deploy
```

Or manually:

```bash
python -c "from pipeline import deploy_to_app; deploy_to_app(...)"
```

## Git Tracking

These files ARE tracked in git for convenience. The W&B run ID in the header
provides traceability to the exact training run that produced them.

If you see a diff after pulling, it means someone trained a new model.
'''
    
    with open(readme_path, "w") as f:
        f.write(content)
    
    return readme_path
